[build]
  publish = "build"
  command = "yarn run build"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Strict-Transport-Security = "max-age=2592000"
    Content-Security-Policy = "connect-src 'self';"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "accelerometer=(), camera=(), geolocation=(), gyroscope=(), magnetometer=(), microphone=(), interest-cohort=()"

[[headers]]
  for = "*.js"
  [headers.values]
    cache-control = '''
    max-age=31536000,
    public,
    immutable'''

[[headers]]
  for = "*.css"
  [headers.values]
    cache-control = '''
    max-age=31536000,
    public,
    immutable'''

[[headers]]
  for = "*.png"
  [headers.values]
    cache-control = '''
    max-age=31536000,
    public,
    immutable'''

[[headers]]
  for = "*.svg"
  [headers.values]
    cache-control = '''
    max-age=31536000,
    public,
    immutable'''