[build]
  publish = "build"
  command = "yarn run build"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Content-Security-Policy = "form-action https:"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Strict-Transport-Security = "max-age=2592000"

[[headers]]
  for = "*.js"
  [headers.values]
	   cache-control = '''
	   max-age=31536000,
	   public,
	   immutable'''

[[headers]]
  for = "*.css"
  [headers.values]
	   cache-control = '''
	   max-age=31536000,
	   public,
	   immutable'''

[[headers]]
  for = "*.png"
  [headers.values]
	   cache-control = '''
	   max-age=31536000,
	   public,
	   immutable'''

[[headers]]
  for = "*.svg"
  [headers.values]
	   cache-control = '''
	   max-age=31536000,
	   public,
	   immutable'''

[[redirects]]
  from = "https://puebi.netlify.app/*"
  to = "https://puebi.js.org/:splat"
  status = 301
  force = true