module.exports = {
  docs: [
    'puebi',
    {
      type: 'category',
      label: 'Pemakaian Huruf',
      items: [
        'huruf',
        'huruf/abjad',
        'huruf/vokal',
        'huruf/konsonan',
        'huruf/diftong',
        'huruf/gabungan',
        'huruf/kapital',
        'huruf/miring',
        'huruf/tebal',
      ],
    },
    {
      type: 'category',
      label: 'Penulisan Kata',
      items: [
        'kata',
        'kata/dasar',
        'kata/berimbuhan',
        'kata/ulang',
        'kata/gabungan',
        'kata/pemenggalan',
        'kata/depan',
        'kata/partikel',
        'kata/singkatan',
        'kata/angka',
        'kata/ganti',
        'kata/sandang',
      ],
    },
    {
      type: 'category',
      label: 'Pemakaian Tanda Baca',
      items: [
        'tanda',
        'tanda/titik',
        'tanda/koma',
        'tanda/titik-koma',
        'tanda/titik-dua',
        'tanda/hubung',
        'tanda/pisah',
        'tanda/tanya',
        'tanda/seru',
        'tanda/elipsis',
        'tanda/petik',
        'tanda/petik-tunggal',
        'tanda/kurung',
        'tanda/kurung-siku',
        'tanda/garis-miring',
        'tanda/penyingkat',
      ],
    },
    'unsur-serapan',
  ],
}
